#!/bin/sh
# ~/.config/now/events.sh
# Script which will define events

export now_event_1=""
export now_event_2=""
export now_event_3=""
export now_event_4=""
export now_event_5=""
export now_event_6=""
export now_event_7=""
export now_event_8=""
export now_event_9=""
export now_event_10=""
export now_event_11=""
export now_event_12=""
export now_event_13=""
export now_event_14=""
export now_event_15=""
export now_event_16=""
export now_event_17=""
export now_event_18=""
export now_event_19=""
export now_event_20=""
export now_event_21=""
export now_event_22=""
export now_event_23=""
export now_event_24=""
export now_event_25=""
